#!/bin/sh
#file name: accessday
#must state number of days prior eg ./accessday 1 - for yesterday ./accessday 0 for today

datetag=date -v-$1d "+%d/%b/%Y" /
tail -n 500000 /var/log/httpd-access.log | grep $datetag /
| grep -v xxx.xxx.xxx | grep -v yyy.yyy.yyy /
| awk '{print $1}' | awk -F'.' '{print $1 "." $2 "." $3}' | sed s/' '/\n/g | sort | uniq -c | sort -n
