#!/bin/sh
#file name: accessday
#must state number of days prior eg ./accessday 1 - for yesterday ./accessday 0 for today

datetag=`date -v-$1d "+%d/%b/%Y"`
tail -n 500000 /var/log/httpd-access.log | grep $datetag \
| grep -v  66.249.79 | grep -v 66.249.72 | grep -v 66.249.68 | grep -v  52.167.1    44 | grep -v  40.77 | grep -v  157.55.39 | grep -v  207.46.13 | grep -v 66.249.6    4 | grep -v 104.224.114 \
| awk '{print $1}' | awk -F'.' '{print $1 "." $2}' | sed s/' '/\\n/g | sort | un    iq -c | sort -n
